baseURL = "https://jinrakuki.netlify.com/"
languageCode = "ja-jp"
title = "秦楽記"
theme = "m10c"

[params]
author = "overQ"
description = "秦氏とか神話ことなどを少々"
avatar = "/avatar.jpg"

[[params.social]]
name = "github"
url = "https://github.com/overQrevo/jinrakuki_blog"

[params.style]
darkestColor = "#d35050"
darkColor = "#212121"
lightColor = "#f5e3e0"
lightestColor = "#f5f5f5"
primaryColor = "#fff"
