baseURL = "https://hatarakuki.tokyo/"
languageCode = "ja"
title = "秦楽記"
theme = "m10c"
paginate = 5
summaryLength = 150

[params]
  author = "overQ"
  description = "秦氏とか神話のことなどを少々"
  avatar = "/ovq.jpg"
  images = ["/ovq.jpg"]
  customCSS = ["/css/ovq_custom.css"]

  [[params.social]]
    name = "github"
    url = "https://github.com/overQrevo/jinrakuki_blog"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/overQrevo"

  [params.style]
    darkestColor = "#51151F"
    darkColor = "#212121"
    lightColor = "#f5e3e0"
    lightestColor = "#f5f5f5"
    primaryColor = "#fff"
    
# Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
